ProyectoGrado/Controllers/SolicitudesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiciosDigitalesProy.Models;
using ServiciosDigitalesProy.Catalogos;
using ProyectoGrado.Tags;
using Models.Comun;
using Helper;
using System.Text.RegularExpressions;

namespace ServiciosDigitalesProy.Controllers
{
    [Autenticado]
    public class SolicitudesController : Controller
    {


        [HttpGet]
        [Permiso(Permiso = RolesPermisos.puede_consultar_solicitudes)]
        public ActionResult ConsultarSolicitudes()
        {
            string resultado = "", tipoResultado = "";
            List<Solicitud> solicitudes =  new List<Solicitud>();
            solicitudes = CatalogoSolicitudes.GetInstance().ConsultarSolicitudes(ref resultado, ref tipoResultado);
            TempData["mensaje"] = resultado;
            TempData["estado"] = tipoResultado;
            Session["solicitudes"] = solicitudes;
            return View(solicitudes);
        }

        
        [HttpGet]
        [Permiso(Permiso = RolesPermisos.puede_consultar_elementos)]
        public ActionResult ConsultarElementos()
        {
            string resultado = "", tipoResultado = "";
            List<Elemento> elementos;
            elementos = CatalogoSolicitudes.GetInstance().ConsultarElementos(ref resultado,ref tipoResultado);
            elementos.RemoveAt(0);
            return View("ConsultarElementos", elementos);
        }

        [HttpGet]
        public ActionResult ConsultarElementosModal()
        {
            string resultado = "", tipoResultado = "";
            List<Elemento> elementos;
            elementos = CatalogoSolicitudes.GetInstance().ConsultarElementos(ref resultado, ref tipoResultado);
            elementos.RemoveAt(0);
            return View("ConsultarElementosModal", elementos);
        }

        [HttpGet]
        public ActionResult AsignarElemento(int id)
        {
            Solicitud solicitud = CrearSolicitudVacia();
            solicitud.elemento.id_elemento = id;
            return View("GenerarSolicitud", solicitud);
        }

       

        [HttpGet]
        [Permiso(Permiso = RolesPermisos.puede_ver_detalle_solicitud)]
        public ActionResult VerSolicitud(int id)
        {
            List<Solicitud> solicitudes = Session["solicitudes"] as List<Solicitud>;
            Solicitud solicitud = solicitudes.Find(x => x.id_solicitud == id);
            ViewBag.idSolicitud = solicitud.id_solicitud;
            return View("VerSolicitud", solicitud);
        }

       
        [HttpGet]
        public ActionResult GenerarSolicitud()
        {
            return View(CrearSolicitudVacia());
        }

        [HttpPost]
        public ActionResult GenerarSolicitud(Solicitud solicitud)
        {
            string res = "",tipores = "";
            string resultado = "", tipoResultado = "";
            CatalogoSolicitudes.GetInstance().GenerarSolicitud(solicitud,ref resultado,ref tipoResultado);
            if (tipoResultado == "danger")
            {
                TempData["mensaje"] = "No se ha generado la solicitud correctamente. Verifique la información registrada";
                TempData["estado"] = tipoResultado;
                return View(solicitud);
            }
            else
            {
                TempData["mensaje"] = resultado;
                TempData["estado"] = tipoResultado;
                return View("ConsultarSolicitudes", CatalogoSolicitudes.GetInstance().ConsultarSolicitudes(ref res, ref tipores));
            }

        }


        [HttpGet]
        [Permiso(Permiso = RolesPermisos.puede_cambiar_estado_solicitud)]
        public ActionResult CambiarEstado(string id)
        {
            Solicitud solicitud;
            string resultado = "", tipoResultado = "";
            if (id != "idSeleccionado" && id != "CrearElemento" && id != "GenerarSolicitud")
            {
                int idSolicitud = Convert.ToInt32(id);
                solicitud = CatalogoSolicitudes.GetInstance().ConsultaEstadoSolicitud_X_id(idSolicitud, ref resultado, ref tipoResultado);
                solicitud.id_solicitud = idSolicitud;
                solicitud.estadoSolicitudSelect = new SelectList(CatalogoSolicitudes.GetInstance().ConsultarEstadosSolicitud(), "id", "Descripcion");
                TempData["mensaje"] = resultado;
                TempData["estado"] = tipoResultado;
                TempData["idEstadoActual"] = solicitud.estadoSolicitud.id;
                return View(solicitud);
            }
            else
            {
                
                List<Solicitud> solicitudes = new List<Solicitud>();
                solicitudes = CatalogoSolicitudes.GetInstance().ConsultarSolicitudes(ref resultado, ref tipoResultado);
                TempData["mensaje"] = "Por favor seleccione una opción";
                TempData["estado"] = "danger";
                return View("ConsultarSolicitudes",solicitudes);

            }
        }

        
        [HttpPost]
        public ActionResult ModificarEstadoSolicitud(Solicitud solicitud)
        {
            string res = "", tipores = "";
            string resultado = "", tipoResultado = "";
            CatalogoSolicitudes.GetInstance().CambiarEstadoSolicitud
                                                                (solicitud.id_solicitud, 
                                                                (int)TempData.Peek("idEstadoActual"),
                                                                solicitud.estadoSolicitud.id,
                                                                ref resultado, ref tipoResultado);

            TempData["mensaje"] = resultado;
            TempData["estado"] = tipoResultado;
            return View("ConsultarSolicitudes", CatalogoSolicitudes.GetInstance().ConsultarSolicitudes(ref res, ref tipores));
        }


        [HttpGet]
        [Permiso(Permiso = RolesPermisos.puede_agregar_elemento)]
        public ActionResult CrearElemento()
        {
            Elemento element = new Elemento();
            element.tiposElementoSelect = new SelectList(CatalogoSolicitudes.GetInstance().ConsultarTiposElemento(), "id", "Descripcion");
            element.categoriasElementoSelect = new SelectList(CatalogoSolicitudes.GetInstance().ConsultarCategoriasElemento(), "id", "Descripcion");
            return View(element);
        }

        [HttpPost]
        public ActionResult CrearElemento(Elemento elemento)
        {
            string resultado = "", tipoResultado = "";
            CatalogoSolicitudes.GetInstance().AgregarElemento(elemento,ref resultado,ref tipoResultado);
            TempData["mensaje"] = resultado;
            TempData["estado"] = tipoResultado;
            return View("ConsultarSolicitudes", Session["solicitudes"] as List<Solicitud>);
        }

        [Permiso(Permiso = RolesPermisos.puede_crear_solicitudes)]
        public Solicitud CrearSolicitudVacia()
        {
            string res = "", tipores = "";
            Solicitud solicitud = new Solicitud();
            solicitud.prioridadSolicitudSelect = new SelectList(CatalogoSolicitudes.GetInstance().ConsultarTiposPrioridad(), "id", "Descripcion");
            solicitud.estadoSolicitudSelect = new SelectList(CatalogoSolicitudes.GetInstance().ConsultarEstadosSolicitud(), "id", "Descripcion");
            solicitud.ListaServiciosSelect = new SelectList(CatalogoServicios.GetInstance().ConsultarServicios(ref res, ref tipores), "id_servicio", "descripcion");
            solicitud.ListaClientesSelect = new SelectList(CatalogoUsuarios.GetInstance().ConsultarClientes("", ref res, ref tipores), "idUsuario", "NombresApellidosDocumento");
            return solicitud;
        }
        #region Escalar

        [HttpGet]
        [Permiso(Permiso = RolesPermisos.puede_escalar_solicitud)]
        public ActionResult Escalar(string id)
        {
            string resultado = "", tipoResultado = "";
            if (id != "idSeleccionado" && id != "CrearElemento" && id != "GenerarSolicitud")
            {
                int idSolicitud = Convert.ToInt32(id);
                
                List<Solicitud> solicitudes = Session["solicitudes"] as List<Solicitud>;
                Solicitud solicitud = solicitudes.Find(x => x.id_solicitud == idSolicitud);
                ViewBag.idSolicitud = solicitud.id_solicitud;

                List<Usuario> usuarios;
                usuarios = CatalogoUsuarios.GetInstance().ConsultarEmpleados("", ref resultado, ref tipoResultado);
                for (int i = 0; i < usuarios.Count; i++)
                {
                    if (usuarios[i].estado != "Activo" || (SessionHelper.GetUser().ToString() == usuarios[i].identificacion))
                        usuarios.RemoveAt(i);
                }
                solicitud.ListaEmpleadosSelect = new SelectList(usuarios, "identificacion", "nombres");


                return View(solicitud);
            }else
            {
                List<Solicitud> solicitudes = new List<Solicitud>();
                solicitudes = CatalogoSolicitudes.GetInstance().ConsultarSolicitudes(ref resultado, ref tipoResultado);
                TempData["mensaje"] = "Por favor seleccione una opción";
                TempData["estado"] = "danger";
                return View("ConsultarSolicitudes", solicitudes);
            }
        }


        [HttpPost]
        public ActionResult Escalar(Solicitud solicitud)
        {
            string res = "", tipores = "";
            string resultado = "", tipoResultado = "";
            CatalogoSolicitudes.GetInstance().EscalarSolicitud(solicitud,ref resultado,ref tipoResultado);

            TempData["mensaje"] = resultado;
            TempData["estado"] = tipoResultado;
            return View("ConsultarSolicitudes", CatalogoSolicitudes.GetInstance().ConsultarSolicitudes(ref res, ref tipores));
        }


        #endregion

        [HttpGet]

ProyectoGrado/Views/Solicitudes/AgregarAnotacionModal.cshtml
@model ServiciosDigitalesProy.Models.Solicitud

@{
    Layout = null;
}

<style>
    .panel-body {
        padding: 0px;
    }
    label {
    text-align: left;
}
    textarea {
        width: 250px;
        height: 100px;
    }
</style>
<section class="panel">
    @using (Html.BeginForm("AgregarAnotacion", "Solicitudes", FormMethod.Post, new { @id = "Form1" }))
    {

        <div class="form-horizontal col-md-8">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="form-group">
                    @Html.Label("Código Solicitud:", htmlAttributes: new { @class = "control-label col-md-7" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.id_solicitud, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                    @*@Html.Hidden("id_servicio", Model.id_servicio)*@
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    @Html.Label("Anotación :", htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7 inputGroupContainer">
                        <div class="input-group">
                            @Html.TextAreaFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Descripción", @maxlength = "100", @type = "text" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>            
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-2">
                        <input type="submit" id="Aceptar" value="Aceptar" class="btn btn-success" />
                    </div>
                </div>
            </div>

        </div>
    }
</section>
@Html.Partial("Partials/_Script")
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoGrado/Views/Solicitudes/CambiarEstado.cshtml
@using ServiciosDigitalesProy.Models
@model ServiciosDigitalesProy.Models.Solicitud
@{
    ViewBag.Title = " Solicitudes";
    ViewBag.SubSeccion = "Cambiar Estado de la solicitud #" + Model.id_solicitud;
}

<h3>@ViewBag.SubSeccion</h3>
<div class="col-lg-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="#"><i class="fa fa-th-list"></i>@ViewBag.Title</a></li>
        <li class="active"><a href="#">@ViewBag.SubSeccion</a></li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Estado de la solicitud
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            @using (Html.BeginForm("ModificarEstadoSolicitud", "Solicitudes", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <label>Código Solicitud</label>
                                    @Html.TextBox("Código Solicitud", Model.id_solicitud, new { @class = "form-control", @disabled = "disabled" })
                                </div>
                                @Html.Hidden("id_solicitud", Model.id_solicitud)

                                <div class="form-group">
                                    <label>Estado Actual</label>
                                    @Html.TextBox("Estado Actual", Model.estadoSolicitud.Descripcion, new { @class = "form-control", @disabled = "disabled" })
                                </div>

                                <div class="form-group">
                                    <label>Tipos de Estado</label>
                                    @Html.DropDownListFor(x => x.estadoSolicitud.id, Model.estadoSolicitudSelect, null, new { @class = "form-control" })
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <button type="submit" name="submitButton" id="submitButton" class="btn btn-success">Actualizar</button>

                                    </div>
                                    <div class="col-md-4">
                                        @Html.ActionLink("Volver", "ConsultarSolicitudes", null, new { @class = "btn btn-primary" })
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->
</div>
@if ((string)TempData["mensaje"] != null || (string)TempData["mensaje"] != "")
{
    <script>
        $(function (msg) {
            $.bootstrapGrowl('@((string)TempData["mensaje"])', {
                type: '@((string)TempData["estado"])',
                offset: { from: 'top', amount: 100 }
            });
        });
    </script>
}

ProyectoGrado/Views/Solicitudes/ConsultaElemento.cshtml
@model ServiciosDigitalesProy.Models.Elemento

@{
    ViewBag.Title = " Solicitudes";
    ViewBag.SubSeccion = "Elemento Solicitud  Cliente " + ViewBag.NombreCliente;
}

<h3>@ViewBag.SubSeccion</h3>
<div class="col-lg-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="#"><i class="fa fa-th-list"></i>@ViewBag.Title</a></li>
        <li class="active"><a href="#">Elemento Solicitud</a></li>
    </ul>
    <!--breadcrumbs end -->
</div>
<section class="panel">
    <div class="panel-body">
        <div class="tab-content">
            <div id="home-3" class="tab-pane active">
                <!-- page start-->
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
                                <div class="row">
                                </div>
                                <ul class="nav nav-tabs pull-right">
                                    <li class="active">
                                        <a data-toggle="tab" href="#home-3">
                                            <i class="fa fa-circle" aria-hidden="true"></i>
                                            @ViewBag.SubSeccion
                                        </a>
                                    </li>
                                </ul>

                            </header>
                            <div class="col-lg-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        Elemento 
                                    </div>
                                    <!-- /.panel-heading -->
                                    <div class="panel-body">
                                        <table width="100%" class="table table-striped table-bordered table-hover" id="table-inicial">
                                            <thead>
                                                <tr>
                                                    <td>
                                                        <b>Descripción</b>
                                                    </td>
                                                    <td>
                                                        <b>Serial</b>
                                                    </td>
                                                    <td>
                                                        <b>Modelo</b>
                                                    </td>
                                                    <td>
                                                        <b>Marca</b>
                                                    </td>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(x => x.tipoElemento.Descripcion)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(x => x.serial)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(x => x.modelo)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(x => x.marca)
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- /.panel-body -->
                                </div>
                                <div class="form-group">
                                    <div class="col-md-2">
                                        @Html.ActionLink("Volver", "VolverDetallesProducto", new  { @*d = Model.id_producto*@ }, new { @class = "btn btn-primary" })
                                    </div>
                                </div>
                                <!-- /.panel -->
                            </div>
                        </section>
                    </div>
                </div>
                <!-- page end-->
            </div>
        </div>
    </div>
</section>
@if ((string)TempData["mensaje"] != null || (string)TempData["mensaje"] != "")
{
    <script>
        $(function (msg) {
            $.bootstrapGrowl('@((string)TempData["mensaje"])', {
                type: '@((string)TempData["estado"])',
                offset: { from: 'top', amount: 100 }
            });
        });
    </script>
}

ProyectoGrado/Views/Solicitudes/ConsultarElementos.cshtml
@model IEnumerable<ServiciosDigitalesProy.Models.Elemento>

@{
    ViewBag.Title = " Solicitudes";
    ViewBag.SubSeccion = "Consulta de elementos";
}

<h3>@ViewBag.SubSeccion</h3>
<div class="col-lg-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="#"><i class="fa fa-th-list"></i>@ViewBag.Title</a></li>
        <li class="active"><a href="#">Elemento Solicitud</a></li>
    </ul>
    <!--breadcrumbs end -->
</div>
<section class="panel">
    <div class="panel-body">
        <div class="tab-content">
            <div id="home-3" class="tab-pane active">
                <!-- page start-->
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading tab-bg-dark-navy-blue tab-right ">
                                <div class="row">
                                </div>
                                <ul class="nav nav-tabs pull-right">
                                    <li class="active">
                                        <a data-toggle="tab" href="#home-3">
                                            <i class="fa fa-circle" aria-hidden="true"></i>
                                            @ViewBag.SubSeccion
                                        </a>
                                    </li>
                                </ul>

                            </header>
                            <div class="col-lg-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <b>Elemento</b>
                                    </div>
                                    <!-- /.panel-heading -->
                                    <div class="panel-body">
                                        <table width="100%" class="table table-striped table-bordered table-hover" id="table-inicial">
                                            <thead>
                                                <tr>
                                                    <td>
                                                        <b>Id</b>
                                                    </td>
                                                    <td>
                                                        <b>Categoría</b>
                                                    </td>
                                                    <td>
                                                        <b>Tipo</b>
                                                    </td>
                                                    <td>
                                                        <b>Serial</b>
                                                    </td>
                                                    <td>
                                                        <b>Modelo</b>
                                                    </td>
                                                    <td>
                                                        <b>Marca</b>
                                                    </td>
                                                    <td>
                                                        <b>Serial Batería</b>
                                                    </td>
                                                    <td>
                                                        <b>RAM</b>
                                                    </td>
                                                    <td>
                                                        <b>ROM</b>
                                                    </td>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayFor(x => item.id_elemento)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(x => item.categoriaElemento.Descripcion)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(x => item.tipoElemento.Descripcion)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(x => item.serial)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(x => item.modelo)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(x => item.marca)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(x => item.serialBateria)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(x => item.ram)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(x => item. rom)
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- /.panel-body -->
                                </div>
                                <!-- /.panel -->
                            </div>
                        </section>
                    </div>
                </div>
                <!-- page end-->
            </div>
        </div>
    </div>
</section>
@Html.Partial("Partials/_Script")
@if ((string)TempData["mensaje"] != null || (string)TempData["mensaje"] != "")
{
    <script>
        $(function (msg) {
            $.bootstrapGrowl('@((string)TempData["mensaje"])', {
                type: '@((string)TempData["estado"])',
                offset: { from: 'top', amount: 100 }
            });
        });
    </script>
}

ProyectoGrado/Views/Solicitudes/Escalar.cshtml
@using ServiciosDigitalesProy.Models
@model ServiciosDigitalesProy.Models.Solicitud
@{
    ViewBag.Title = " Solicitudes";
    ViewBag.SubSeccion = "Escalar solicitud # " + Model.id_solicitud;
}

<h3>@ViewBag.SubSeccion</h3>
<div class="col-lg-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="#"><i class="fa fa-th-list"></i>@ViewBag.Title</a></li>
        <li class="active"><a href="#">@ViewBag.SubSeccion</a></li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Escalar Solicitud
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            @using (Html.BeginForm("Escalar", "Solicitudes", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <label>Código Solicitud</label>
                                    @Html.TextBox("Código Solicitud", Model.id_solicitud, new { @class = "form-control", @disabled = "disabled" })
                                </div>
                                @Html.Hidden("id_solicitud", Model.id_solicitud)

                                <div class="form-group">
                                    <label>Descripción</label>
                                    @Html.TextBox("Descripción", Model.descripcion, new { @class = "form-control", @disabled = "disabled" })
                                </div>

                                <div class="form-group">
                                    <label>Escalar A</label>
                                    @Html.DropDownListFor(x => x.idEmpleado, Model.ListaEmpleadosSelect, null, new { @class = "form-control" })
                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        <button type="submit" name="submitButton" id="submitButton" class="btn btn-warning">Escalar</button>
                                    </div>
                                    <div class="col-md-4">
                                        @Html.ActionLink("Volver", "ConsultarSolicitudes", null, new { @class = "btn btn-primary" })
                                    </div>
                                </div>
                               
                            }
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->
</div>
@if ((string)TempData["mensaje"] != null || (string)TempData["mensaje"] != "")
{
    <script>
        $(function (msg) {
            $.bootstrapGrowl('@((string)TempData["mensaje"])', {
                type: '@((string)TempData["estado"])',
                offset: { from: 'top', amount: 100 }
            });
    });
    </script>
}