ProyectoGrado/Models/Inventario/HistoricoInventario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ServiciosDigitalesProy.Models
{
    public class HistoricoInventario
    {
        public HistoricoInventario()
        {
            id_Historico = 0;
            empleado = new Usuario();
            id_inventario = 0;
            fecha = new DateTime();
            descripcion = "";
        }

        public int id_Historico { get; set; }
        public Usuario empleado { get; set; }
        public DateTime fecha { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de \"Descripción\" es obligatorio.")]
        [RegularExpression(@"^[0-9a-zA-ZáéíóÚ.ÁÉÍÓÚñÑ. ]{1,500}$", ErrorMessage = "Los Caracteres especiales no son permitidos y el máximo de caracteres permitidos es 500")]
        public string descripcion { get; set; }
        public int id_inventario { get; set; }
        
    }

    
}

ProyectoGrado/Models/Inventario/Inventario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ServiciosDigitalesProy.Models
{
    public class Inventario
    {
        public Inventario()
        {
            id_inventario = 0;
            cantidadExistencias = 0;
            producto = new Producto();
            historico = new HistoricoInventario();
            fecha = new DateTime();
            sucursal = new Sucursal();
        }

        public int id_inventario { get; set; }

        public Producto producto { get; set; }

        [Range(1, 1000, ErrorMessage = "Debe agregar una cantidad entre 1 y 1000 unidades")]
        public int cantidadExistencias { get; set; }

        public DateTime fecha { get; set; }

        public Sucursal sucursal { get; set; }

        public HistoricoInventario historico { get; set; }



    }

    
}

ProyectoGrado/Models/Inventario/Sucursal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ServiciosDigitalesProy.Models
{
    public class Sucursal
    {
        public Sucursal()
        {
            id_sucursal = 0;
            nombre = "";
            direccion = "";
            ciudad = "";
            telefonoFijo = "";
            telfonoCelular = "";

        }

        public Sucursal(string nombre)
        {
            this.nombre = nombre;
        }
        public Sucursal(int id,string nombre)
        {
            this.id_sucursal = id;
            this.nombre = nombre;
        }
        public int id_sucursal { get; set; }

        [RegularExpression(@"^[0-9a-zA-ZáéíóÚ.ÁÉÍÓÚ@. ]{1,40}$", ErrorMessage = "Los Caracteres especiales no son permitidos.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de \"Nombre\" es obligatorio.")]
        public string nombre { get; set; }

        [RegularExpression(@"^[0-9a-zA-ZáéíóÚ.ÁÉÍÓÚ@. ]{1,40}$", ErrorMessage = "Los Caracteres especiales no son permitidos.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de \"Dirección\" es obligatorio.")]
        public string direccion { get; set; }

        [RegularExpression(@"^[0-9a-zA-ZáéíóÚ.ÁÉÍÓÚ@. ]{1,40}$", ErrorMessage = "Los Caracteres especiales no son permitidos.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de \"Ciudad\" es obligatorio.")]
        public string ciudad { get; set; }


        [Range(11111111, 99999999999, ErrorMessage = "El teléfono debe tener 8 dígitos")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "El Teléfono Fijo debe ser numérico")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de \"Teléfono Fijo\" es obligatorio.")]
        public string telefonoFijo { get; set; }

        [Range(1111111111, 99999999999, ErrorMessage = "El teléfono debe tener 10 dígitos")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "El Teléfono Celular debe ser numérico")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El campo de \"Teléfono Celular\" es obligatorio.")]
        public string telfonoCelular { get; set; }

    }

    
}

ProyectoGrado/Controllers/InventariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiciosDigitalesProy.Models;
using ProyectoGrado.Catalogos;
using ProyectoGrado.Tags;
using System.ComponentModel.DataAnnotations;
using Models.Comun;

namespace ServiciosDigitalesProy.Controllers
{
    [Autenticado]
    public class InventariosController : Controller
    {


        /// <summary>
        /// Consulta las sucursales actuales
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ConsultarSucursales()
        {
            string resultado = "", tipoResultado = "";

            List<Sucursal> sucursales = CatalogoInventarios.GetInstance().ConsultarSucursalesCompleto(ref resultado, ref tipoResultado);
            Session["sucursales"] = sucursales;
            if (tipoResultado != "danger")
            {
                return View("ConsultarSucursales", sucursales);
            }
            else
            {
                TempData["mensaje"] = resultado;
                TempData["estado"] = tipoResultado;
                return RedirectToAction("IndexInterno", "Home");
            }
        }


        /// <summary>
        /// Consulta el inventario de productos que hay en una sucursal específica y muestra
        /// en vista para su edicion
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ConsultarInventarioXSucursal(int id)
        {
            //identificacion = identificacion == "0" ? "" : identificacion;
            string resultado = "", tipoResultado = "";
            List<Inventario> inventarios;
            inventarios = CatalogoInventarios.GetInstance().ConsultarProductosXSucursal(id, ref resultado, ref tipoResultado);

            TempData["mensaje"] = resultado;
            TempData["estado"] = tipoResultado;
            if (tipoResultado == "danger")
            {
                TempData["mensaje"] = resultado;
                TempData["estado"] = tipoResultado;
                return View("ConsultarSucursales", Session["sucursales"] as List<Sucursal>);
            }
            else
            {
                string res = "", tipoRes = "";
                List<Producto> prod = CatalogoProductos.GetInstance().ConsultarProductos("", ref res, ref tipoRes);
                int numProd = prod.Count;
                ViewBag.cantidadProductos = numProd;
                ViewBag.nombreSucursal = inventarios.Count > 0 ? inventarios[0].sucursal.nombre : "";
                Session["nombreSucursalInventario"] = ViewBag.nombreSucursal;
                ViewBag.idSucursal = id;
                Session["idSucursal"] = id;
                return View(inventarios);
            }
        }

        [HttpGet]
        public ActionResult VolverVistaInventarioXSucursal()
        {
            string res = "", tipoRes = "";
            List<Producto> prod = CatalogoProductos.GetInstance().ConsultarProductos("", ref res, ref tipoRes);
            int numProd = prod.Count;
            ViewBag.cantidadProductos = numProd;

            List<Inventario> inventarios;
            inventarios = CatalogoInventarios.GetInstance().ConsultarProductosXSucursal((int)Session["idSucursal"], ref res, ref tipoRes);
            ViewBag.nombreSucursal = inventarios.Count > 0 ? inventarios[0].sucursal.nombre : "";
            ViewBag.idSucursal = (int)Session["idSucursal"];
            return View("ConsultarInventarioXSucursal", inventarios);
        }

        /// <summary>
        /// Agrega un producto que no se haya vendido en una sucursal específica
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AgregarProductoASucursal()
        {
            //identificacion = identificacion == "0" ? "" : identificacion;
            string resultado = "", tipoResultado = "";
            List<Producto> productos;
            productos = CatalogoProductos.GetInstance().ConsultarProductos("", ref resultado, ref tipoResultado);

            return View("AgregarProductoASucursal", productos);
        }

        [HttpGet]
        [Permiso(Permiso = RolesPermisos.Puede_Crear_Espacio_En_sucursal)]
        public ActionResult AsignarEspacioProductoASucursal(int id)
        {
            //identificacion = identificacion == "0" ? "" : identificacion;
            string resultado = "", tipoResultado = "";
            CatalogoInventarios.GetInstance().AsignarEspacioProductoASucursal(id, (int)Session["idSucursal"], ref resultado, ref tipoResultado);

            TempData["mensaje"] = resultado;
            TempData["estado"] = tipoResultado;

            if (tipoResultado == "danger")
            {
                return RedirectToAction("AgregarProductoASucursal");
            }

            string res = "", tipoRes = "";
            List<Producto> prod = CatalogoProductos.GetInstance().ConsultarProductos("", ref res, ref tipoRes);
            int numProd = prod.Count;
            ViewBag.cantidadProductos = numProd;

            List<Inventario> inventarios;
            inventarios = CatalogoInventarios.GetInstance().ConsultarProductosXSucursal((int)Session["idSucursal"], ref resultado, ref tipoResultado);
            ViewBag.nombreSucursal = inventarios.Count > 0 ? inventarios[0].sucursal.nombre : "";
            ViewBag.idSucursal = id;
            return View("ConsultarInventarioXSucursal", inventarios);
        }



        [HttpGet]
        [Permiso(Permiso = RolesPermisos.Puede_Trasladar_Producto)]
        public ActionResult TrasladarProductoASucursal(int id)
        {
            string resultado = "", tipoResultado = "";
            List<Inventario> inventarios = CatalogoInventarios.GetInstance().ConsultarInventarios("", ref resultado, ref tipoResultado);
            Inventario inventario = inventarios.Find(x => x.id_inventario == id);
            inventario.producto.sucursalesSelect = new SelectList(CatalogoProductos.GetInstance().ConsultarSucursales(), "id_sucursal", "nombre");
            ViewBag.nombreSucursal = (string)Session["nombreSucursalInventario"];
            return View(inventario);

        }

        /// <summary>
        /// TRASLADA UN PRODUCTO DE UNA SUCURSAL A OTRA 
        /// </summary>
        /// <param name="inventario"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult TrasladarProductoASucursal(Inventario inventario)
        {
            string resultado = "", tipoResultado = "";
            int idSucursalActual = (int)Session["idSucursal"];

            if (inventario.producto.cantid == null)
            {
                TempData["mensaje"] = "El Campo Cantidad no puede estar vacio";
                TempData["estado"] = "danger";


                string res = "", tipoRes = "";
                List<Inventario> inventarios = CatalogoInventarios.GetInstance().ConsultarInventarios("", ref res, ref tipoRes);
                Inventario inventarioo = inventarios.Find(x => x.id_inventario == inventario.id_inventario);
                inventarioo.producto.sucursalesSelect = new SelectList(CatalogoProductos.GetInstance().ConsultarSucursales(), "id_sucursal", "nombre");
                ViewBag.nombreSucursal = (string)Session["nombreSucursalInventario"];
                return View(inventarioo);
            }

            if (idSucursalActual == inventario.sucursal.id_sucursal)
            {
                TempData["mensaje"] = "No se pueden realizar traslados a la misma sucursal origen";
                TempData["estado"] = "danger";


                string res = "", tipoRes = "";
                List<Inventario> inventarios = CatalogoInventarios.GetInstance().ConsultarInventarios("", ref res, ref tipoRes);
                Inventario inventarioo = inventarios.Find(x => x.id_inventario == inventario.id_inventario);
                inventarioo.producto.sucursalesSelect = new SelectList(CatalogoProductos.GetInstance().ConsultarSucursales(), "id_sucursal", "nombre");
                ViewBag.nombreSucursal = (string)Session["nombreSucursalInventario"];
                return View(inventarioo);
            }

            if (inventario.cantidadExistencias == 0)
            {
                TempData["mensaje"] = "No se pueden realizar traslados del producto.  Verifique la cantidad disponible en inventario";
                TempData["estado"] = "danger";

                string res = "", tipoRes = "";
                List<Producto> prod = CatalogoProductos.GetInstance().ConsultarProductos("", ref res, ref tipoRes);
                int numProd = prod.Count;
                ViewBag.cantidadProductos = numProd;

                List<Inventario> inventarios;
                inventarios = CatalogoInventarios.GetInstance().ConsultarProductosXSucursal((int)Session["idSucursal"], ref resultado, ref tipoResultado);
                ViewBag.nombreSucursal = inventarios.Count > 0 ? inventarios[0].sucursal.nombre : "";
                ViewBag.idSucursal = (int)Session["idSucursal"];
                return View("ConsultarInventarioXSucursal", inventarios);
            }

            if (Convert.ToInt32(inventario.producto.cantid) < 0)
            {
                TempData["mensaje"] = "el valor de la cantidad de unidades a trasladar no puede ser menor a cero";
                TempData["estado"] = "danger";
                string res = "", tipoRes = "";
                List<Inventario> inventarios = CatalogoInventarios.GetInstance().ConsultarInventarios("", ref res, ref tipoRes);
                Inventario inventarioo = inventarios.Find(x => x.id_inventario == inventario.id_inventario);
                inventarioo.producto.sucursalesSelect = new SelectList(CatalogoProductos.GetInstance().ConsultarSucursales(), "id_sucursal", "nombre");
                ViewBag.nombreSucursal = (string)Session["nombreSucursalInventario"];
                return View(inventarioo);
            }

ProyectoGrado/Views/Inventarios/ActualizarInventarioXProducto.cshtml
@using ServiciosDigitalesProy.Models
@model ServiciosDigitalesProy.Models.Inventario
@{
    ViewBag.Title = " Inventarios";
    ViewBag.SubSeccion = "Actualizar Inventario del producto";
}

<h3>@ViewBag.SubSeccion</h3>
<div class="col-lg-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="#"><i class="fa fa-th-list"></i>@ViewBag.Title</a></li>
        <li class="active"><a href="#">@ViewBag.SubSeccion</a></li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Datos del Inventario
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            @using (Html.BeginForm("ActualizarInventarioXProducto", "Inventarios", FormMethod.Post))
                            {
                                @Html.Hidden("id_inventario", Model.id_inventario)
                                <div class="form-group">
                                    <label>Código del Producto</label>
                                    @Html.TextBox("producto.id_producto", Model.producto.id_producto, new { @class = "form-control", @disabled = "disabled" })
                                </div>
                                @Html.Hidden("producto.id_producto", Model.producto.id_producto)

                                <div class="form-group">
                                    <label>Cantidad Existencias Actual</label>
                                    @Html.TextBox("identificacion", Model.cantidadExistencias, new { @class = "form-control", @disabled = "disabled" })
                                </div>

                                <div class="form-group">
                                    <label>Cantidad de unidades a adicionar</label>
                                    @Html.TextBox("cantidadExistencias", Model.cantidadExistencias, new { @class = "form-control",@type ="number" })
                                    @Html.ValidationMessageFor(model => Model.cantidadExistencias, "", new { @class = "text-danger" })
                                </div>


                                <div class="row">
                                    <div class="col-md-5">
                                        <button type="submit" name="submitButton" id="submitButton" class="btn btn-success">Actualizar</button>
                                    </div>
                                    <div class="col-md-4">
                                        @Html.ActionLink("Volver", "VolverVistaInventarioXSucursal", null, new { @class = "btn btn-primary" })
                                    </div>
                                </div>
                               
                            }
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->


</div>

@if ((string)TempData["mensaje"] != null || (string)TempData["mensaje"] != "")
{
    <script>
        $(function (msg) {
            $.bootstrapGrowl('@((string)TempData["mensaje"])', {
                type: '@((string)TempData["estado"])',
                offset: { from: 'top', amount: 100 }
            });
        });
    </script>
}

ProyectoGrado/Views/Inventarios/AdicionarBajas.cshtml
@model ServiciosDigitalesProy.Models.Inventario
@{
    ViewBag.Title = " Inventarios";
    ViewBag.SubSeccion = "Agregar Baja(s)";
}

<style>
    textarea {
        width: 300px;
        height: 150px;
    }

    .form-horizontal .control-label {
        text-align: left;
    }
</style>
<h3>@ViewBag.SubSeccion</h3>
<div class="col-lg-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="#"><i class="fa fa-th-list"></i>@ViewBag.Title</a></li>
        <li class="active"><a href="#">@ViewBag.SubSeccion</a></li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Agregar Baja(s)
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("AdicionarBajas", "Inventarios", FormMethod.Post, new { @id = "Form1" }))
                            {
                                @Html.HiddenFor(model=>model.id_inventario)
                                <div class="form-horizontal col-md-10">
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="row">
                                        <div class="form-group">
                                            @Html.Label("Código Producto:", htmlAttributes: new { @class = "control-label col-md-5" })
                                            <div class="col-md-5">
                                                @Html.EditorFor(model => model.producto.id_producto, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            @Html.Label("Nombre Producto:", htmlAttributes: new { @class = "control-label col-md-5" })
                                            <div class="col-md-7">
                                                @Html.EditorFor(model => model.producto.nombre, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            @Html.Label("Número de Bajas:", htmlAttributes: new { @class = "control-label col-md-5" })
                                            <div class="col-md-5">
                                                @Html.EditorFor(model => model.cantidadExistencias, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                                            </div>
                                            @Html.ValidationMessageFor(model => model.cantidadExistencias, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="row">
                                        @Html.Label("Motivo de la baja:", htmlAttributes: new { @class = "control-label col-md-8" })
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-7 inputGroupContainer">
                                                <div class="input-group">
                                                    @Html.TextAreaFor(model => model.historico.descripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Descripción" } })
                                                </div>
                                                @Html.ValidationMessageFor(model => model.historico.descripcion, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    @*<div class="row">
                                        <div class="col-md-4">
                                            <button type="submit" name="submitButton" id="submitButton" class="btn btn-success">Actualizar</button>
                                        </div>
                                        <div class="col-md-4">
                                            @Html.ActionLink("Volver", "ConsultarSolicitudes", null, new { @class = "btn btn-primary" })
                                        </div>
                                    </div>*@

                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-3">
                                                <input type="submit" id="Aceptar" value="Aceptar" class="btn btn-success" />
                                            </div>
                                            <div class="col-md-2">
                                                @Html.ActionLink("Volver", "ConsultarInventariosBajas", new { identificacion = ViewBag.idInventario == null ? "" : ViewBag.idInventario }, new { @class = "btn btn-primary" })
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            }
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->
</div>
@if ((string)TempData["mensaje"] != null || (string)TempData["mensaje"] != "")
{
    <script>
        $(function (msg) {
            $.bootstrapGrowl('@((string)TempData["mensaje"])', {
                type: '@((string)TempData["estado"])',
                offset: { from: 'top', amount: 100 }
            });
        });
    </script>
}

ProyectoGrado/Views/Inventarios/AgregarAnotacionModal.cshtml
@model ServiciosDigitalesProy.Models.Inventario

@{
    Layout = null;
}

<style>
    .panel-body {
        padding: 0px;
    }
    label {
    text-align: left;
}
    textarea {
        width: 250px;
        height: 100px;
    }
</style>
<section class="panel">
    @using (Html.BeginForm("AgregarAnotacionInvent", "Inventarios", FormMethod.Post, new { @id = "Form1" }))
    {

        <div class="form-horizontal col-md-8">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="form-group">
                    @Html.Label("Código Inventario:", htmlAttributes: new { @class = "control-label col-md-7" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.id_inventario, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    @Html.Label("Anotación :", htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7 inputGroupContainer">
                        <div class="input-group">
                            @Html.TextAreaFor(model => model.historico.descripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Descripción", @maxlength = "100", @type = "text" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.historico.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>            
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-2">
                        <input type="submit" id="Aceptar" value="Aceptar" class="btn btn-success" />
                    </div>
                </div>
            </div>

        </div>
    }
</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoGrado/Views/Inventarios/AgregarAnotacionModalBajas.cshtml
@model ServiciosDigitalesProy.Models.Inventario

@{
    Layout = null;
}

<style>
    .panel-body {
        padding: 0px;
    }
    label {
    text-align: left;
}
    textarea {
        width: 250px;
        height: 100px;
    }
</style>
<section class="panel">
    @using (Html.BeginForm("AgregarAnotacionInventBajas", "Inventarios", FormMethod.Post, new { @id = "Form1" }))
    {

        <div class="form-horizontal col-md-8">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="form-group">
                    @Html.Label("Código Inventario:", htmlAttributes: new { @class = "control-label col-md-7" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.id_inventario, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    @Html.Label("Anotación :", htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7 inputGroupContainer">
                        <div class="input-group">
                            @Html.TextAreaFor(model => model.historico.descripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Descripción", @maxlength = "100", @type = "text" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.historico.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>            
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-2">
                        <input type="submit" id="Aceptar" value="Aceptar" class="btn btn-success" />
                    </div>
                </div>
            </div>

        </div>
    }
</section>
@Html.Partial("Partials/_Script")
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}