ProyectoGrado/Controllers/ServiciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiciosDigitalesProy.Models;
using ServiciosDigitalesProy.Catalogos;
using ProyectoGrado.Tags;
using Models.Comun;

namespace ServiciosDigitalesProy.Controllers
{
    [Autenticado]
    public class ServiciosController : Controller
    {

        [HttpGet]
        [PermisoAttribute(Permiso = RolesPermisos.puede_adicionar_servicio)]
        public ActionResult AgregarServicio()
        {
            return View("AdicionarServicio");
        }

      
        [HttpPost]
        public ActionResult AgregarServicio(Servicio model)
        {

            string resultado = "", tipoResultado = "";
            if (ModelState.IsValid)
            {
                CatalogoServicios.GetInstance().AgregarServicio(model, out resultado, out tipoResultado);
                TempData["mensaje"] = resultado;
                TempData["estado"] = tipoResultado;
                if (tipoResultado == "danger")
                {
                    return View("AdicionarServicio",model);
                }
                List<Servicio> servicios;
                servicios = CatalogoServicios.GetInstance().ConsultarServicios(ref resultado, ref tipoResultado);
                return View("ConsultaServicios", servicios);
            }

            TempData["mensaje"] = "Por favor verifique los datos ingresados";
            TempData["estado"] = "danger";
            return View("AdicionarServicio");

        }


        [HttpGet]
        public ActionResult ConsultarServicios()
        {
            string resultado = "", tipoResultado = "";
            List<Servicio> servicios;
            servicios = CatalogoServicios.GetInstance().ConsultarServicios(ref resultado, ref tipoResultado);
            TempData["mensaje"] = resultado;
            TempData["estado"] = tipoResultado;
            return View("ConsultaServicios", servicios);
            
        }



        /// <summary>
        /// Muestra la vista del formulario para actualizar servicio
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [PermisoAttribute(Permiso = RolesPermisos.puede_editar_servicio)]
        public ActionResult ModificarServicio(int id)
        {
            string resultado = "", tipoResultado = "";
            List<Servicio> servicios;
            Servicio servicio;
            servicios = CatalogoServicios.GetInstance().ConsultarServicio(id,ref resultado, ref tipoResultado);

            servicio = servicios.First();
            return View("ModificarServicio", servicio);
        }

        /// <summary>
        /// Actualiza el servicio seleccionado
        /// </summary>
        /// <param name="prod"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateServicio(Servicio servicio)
        {
            string resultado = "", tipoResultado = "";
            string res="", tipoRes="";
            if (ModelState.IsValid)
            {
                CatalogoServicios.GetInstance().ModificarServicio(servicio, ref res, ref tipoRes);
                List<Servicio> servicios;
                servicios = CatalogoServicios.GetInstance().ConsultarServicios(ref resultado, ref tipoResultado);
                TempData["mensaje"] = res;
                TempData["estado"] = tipoRes;

                return View("ConsultaServicios", servicios);

            }

            return RedirectToAction("ModificarServicio", servicio.id_servicio);
        }


        [HttpGet]
        public ActionResult VolverDetallesServicio()
        {
            string resultado = "", tipoResultado = "";
            List<Servicio> servicios;
            servicios = CatalogoServicios.GetInstance().ConsultarServicios(ref resultado, ref tipoResultado);
            return View("ConsultaServicios", servicios);
        }



    }
}

ProyectoGrado/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiciosDigitalesProy.Models;
using ProyectoGrado.Catalogos;
using ServiciosDigitalesProy.Catalogos;
using ProyectoGrado.Tags;
using System.ComponentModel.DataAnnotations;
using Rotativa;
using Models.Comun;

namespace ServiciosDigitalesProy.Controllers
{
    [Autenticado]
    public class VentasController : Controller
    {
        //public Factura factura;

        [HttpGet]
        [PermisoAttribute(Permiso = RolesPermisos.puede_crear_factura)]
        public ActionResult CrearFactura()
        {
            string resultado = "", tipoResultado = "";
            int idFactura = CatalogoVentas.GetInstance().ObtenerIdUltimaFacturaGenerada(ref resultado, ref tipoResultado) + 1;
            DateTime horaActual = DateTime.Now;
            if (idFactura > 1)
            {
                Factura factura = new Factura(idFactura, horaActual);
                Session["Factura"] = factura;
                TempData["mensaje"] = resultado;
                TempData["estado"] = tipoResultado;
                return View(factura);
            }
            else
            {
                TempData["mensaje"] = "No se ha podido iniciar la creación de factura. Intente más tarde";
                TempData["estado"] = "danger";
                return RedirectToAction("IndexInterno", "Home");
            }
        }


        /// <summary>
        /// Consulta la lista de clientes y la agrega aL MODAL
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult BuscarClientes()
        {
            Factura factura = Session["Factura"] as Factura;
            string resultado = "", tipoResultado = "";
            List<Usuario> clientes = CatalogoUsuarios.GetInstance().ConsultarClientes("", ref resultado, ref tipoResultado);
            List<Usuario> clientesActivos = new List<Usuario>();
            Usuario cliente;

            if (clientes != null)
            {
                foreach (var item in clientes)
                {
                    cliente = (item.estado == "Activo") ? item : null;
                    if (cliente != null)
                    {
                        clientesActivos.Add(cliente);
                    }
                    cliente = null;
                }

                return View(clientesActivos);
            }
            else
            {
                TempData["mensaje"] = "No hay clientes registrados en base de datos.";
                TempData["estado"] = "danger";
                return View("CrearFactura", factura);
            }
        }


        [HttpGet]
        public ActionResult AsignarCliente(string id)
        {
            string resultado = "", tipoResultado = "";
            Factura factura = Session["Factura"] as Factura;
            List<Usuario> Clientes = CatalogoUsuarios.GetInstance().ConsultarClientes(id, ref resultado, ref tipoResultado);
            Usuario cliente = Clientes.Find(x => x.identificacion == id);

            if (factura.cliente.identificacion == "")
            {
                factura.cliente = cliente;
                factura.cliente.NombresApellidos = cliente.nombres + " " + cliente.apellidos;
                TempData["mensaje"] = "Cliente Asignado Correctamente";
                TempData["estado"] = "success";
                Session["Factura"] = factura;
            }
            else
            {
                TempData["mensaje"] = "Ya existe un cliente asociado a esta Factura";
                TempData["estado"] = "danger";
            }
            return View("CrearFactura", factura);


        }


        /// <summary>
        ///  ABRE EL MODAL PARA ADICIONAR PRODUCTO
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult BuscarProducto()
        {
            string resultado = "", tipoResultado = "";
            Factura factura = Session["Factura"] as Factura;
            //List<Producto> productos = CatalogoProductos.GetInstance().ConsultarProductos("", ref resultado, ref tipoResultado);
            List<Producto> productos = CatalogoProductos.GetInstance().ConsultarProductosXSucursalSegunEmpleado(ref resultado, ref tipoResultado);
            List<Inventario> inventarios = CatalogoInventarios.GetInstance().ConsultarInventarios("", ref resultado, ref tipoResultado);

            List<Producto> productosDisponibles = new List<Producto>();
            //Inventario temp = null;

            if (productos != null)
            {
                foreach (var item in productos)
                {
                    if (Convert.ToInt32(item.cantid) > 0)
                    {
                        //temp = inventarios.Find(x => x.producto.id_producto == producto.id_producto);
                        //producto.cantid = (temp.cantidadExistencias).ToString();
                        productosDisponibles.Add(item);
                    }
                }

                Session["Productos"] = productosDisponibles;
                return View(productosDisponibles);
            }
            else
            {
                TempData["mensaje"] = "No hay Productos registrados en base de datos, Comuniquese con el administrador y verifique inventario";
                TempData["estado"] = "danger";
                return View("CrearFactura", factura);
            }
        }


        /// <summary>
        /// AGREGA UN PRODUCTO SELECCIONADO EN EL MODAL A LA VISTA PRINCIPAL DE CREACION DE FACTURA
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AdicionarProductoAFactura(int id)
        {
            Factura factura = Session["Factura"] as Factura;
            List<Producto> productos = Session["Productos"] as List<Producto>;
            Producto producto = productos.Find(x => x.id_producto == id);

            DetalleFacturaProducto detalle;
            detalle = factura.listaDetallesProducto.Find(x => x.producto.id_producto == id);
            if (detalle == null)
            {
                factura.listaDetallesProducto.Add(new DetalleFacturaProducto
                {
                    producto = producto
                });
            }
            else
            {
                TempData["mensaje"] = "Ya se encuentra un item del mismo producto en la factura";
                TempData["estado"] = "info";
                return View("CrearFactura", factura);
            }

            TempData["mensaje"] = "Recuerda ingresar la cantidad del producto a vender";
            TempData["estado"] = "info";
            Session["Factura"] = factura;
            return View("CrearFactura", factura);
        }

        /// <summary>
        /// CONSULTA LAS SOLICITUDES ASOCIADAS AL CLIENTE DE LA FACTURA Y LAS ENVIA A LA VISTA MODAL
        /// </summary>
        /// <returns></returns>

        [HttpGet]
        public ActionResult BuscarSolicitudes()
        {
            Factura factura = Session["Factura"] as Factura;
            string resultado = "", tipoResultado = "";
            List<Solicitud> solicitudes = CatalogoSolicitudes.GetInstance().ConsultarSolicitudes(ref resultado, ref tipoResultado);
            List<Solicitud> solicitudesClientefactura = new List<Solicitud>();
            Solicitud solicitud;
            if (solicitudes != null)
            {
                foreach (var item in solicitudes)
                {
                    solicitud = (item.cliente.identificacion == factura.cliente.identificacion) ? item : null;
                    if (solicitud != null && solicitud.estadoSolicitud.Descripcion!="Anulada" )
                    {
                        solicitudesClientefactura.Add(solicitud);
                    }
                    solicitud = null;
                }
                ViewBag.NombreCliente = factura.cliente.NombresApellidos;
                Session["Solicitudes"] = solicitudesClientefactura;
                return View(solicitudesClientefactura);

            }
            else
            {
                TempData["mensaje"] = "No hay solicitudes registradas en base de datos";
                TempData["estado"] = "danger";
                return View("CrearFactura", factura);
            }
        }

        /// <summary>
        /// AGREGA UNA SOLICITUD SELECCIONADA DESDE EL MODAL A LA FACTURA 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AdicionarSolicitudAFactura(int id)
        {
            Factura factura = Session["Factura"] as Factura;
            List<Solicitud> solicitudes = Session["Solicitudes"] as List<Solicitud>;
            Solicitud solicitud = solicitudes.Find(x => x.id_solicitud == id);

            DetalleFacturaSolicitud detalle;
            detalle = factura.listaDetallesSolicitud.Find(x => x.solicitud.id_solicitud == id);
            if (detalle == null)
            {
                factura.listaDetallesSolicitud.Add(new DetalleFacturaSolicitud
                {
                    solicitud = solicitud
                });
            }
            else
            {
                TempData["mensaje"] = "Ya se encuentra la misma solicitud en la factura";
                TempData["estado"] = "info";
                return View("CrearFactura", factura);
            }

            TempData["mensaje"] = "Solicitud agregada Correctamente";
            TempData["estado"] = "success";
            Session["Factura"] = factura;
            return View("CrearFactura", factura);
        }


        /// <summary>
        /// GENERA LA FACTURA Y LA ALISTA PARA MOSTRARLA AL USUARIO ANTES DE GUARDARLA EN BASE DE DATOS
        /// TAMBIEN SE VALIDA EN STOCK Y SE REALIZAN CÁLCULOS PARA EL VALOR TOTAL DE LA FACTURA
        /// </summary>
        /// <param name="facturaa"></param>

ProyectoGrado/Views/Shared/_Footer.cshtml
    <div class="row">
        <div class=" col-md-offset-1">
            <div class="footer-copyright" style="color: darkgray;    text-align: center;">
                <br>
                &copy;  @DateTime.Now.Year - Portal Web - Jonathan Muñoz - Carlos Ortiz
            </div>
        </div>
    </div>

ProyectoGrado/Views/Shared/_Head.cshtml
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="cache-control" content="no-cache"/>
<title>@ViewBag.Title - Servicios Digitales SAS</title>
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/bootstrap")

ProyectoGrado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_Head")
</head>
<body>
    <section id="container">
        @Html.Partial("_SidebarTopbar")

                    <section id="main-content" style="margin-left:240px; margin-top:105px; margin-right:20px;">
            
                        <section class="wrapper">
                            @RenderBody()
                        </section>
                        <footer>
                            @Html.Partial("_Footer")
                        </footer>
                    </section>
        <!--main content end-->
    </section>
    <!--Section Scripts-->
    
        @Html.Partial("_Scripts")
        @RenderSection("scripts", required: false)
        <!--Section Scripts-->
</body>


</html>

ProyectoGrado/Views/Shared/_Scripts.cshtml
@*@Scripts.Render("~/bundles/jquery")*@
@*@Scripts.Render("~/bundles/bootstrap")*@
@Scripts.Render("~/bundles/Personalizacion")

ProyectoGrado/Views/Shared/_SidebarTopbar.cshtml
<header class="header white-bg">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


            <a href="~/Home/IndexLogo" class="logo" onclick="location.reload();">
                <img src="@Url.Content("/Xcore/Imagenes/SERVICIOS DIGITALES logo1.png")" title="Servicios Digitales" style="width:inherit;height:80px;margin-top:2px;margin-left: 20px;" />
            </a>
        </div>
        <!-- Top Menu Items -->



        <ul class="nav navbar-right top-nav">
            <li class="dropdown open">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-home"></i> Sede<b> @CatalogoUsuarios.GetInstance().ConsultarNombreSucursalEmpleado()</b></a>
            </li>



            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                <ul class="dropdown-menu message-dropdown">
                    <li class="message-preview">
                        <a href="#">
                            <div class="media">
                                <span class="pull-left">
                                    <img class="media-object" src="http://placehold.it/50x50" alt="">
                                </span>
                                <div class="media-body">
                                    <h5 class="media-heading">
                                        <strong>jomuva</strong>
                                    </h5>
                                    <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="message-preview">
                        <a href="#">
                            <div class="media">
                                <span class="pull-left">
                                    <img class="media-object" src="http://placehold.it/50x50" alt="">
                                </span>
                                <div class="media-body">
                                    <h5 class="media-heading">
                                        <strong>Jonathan</strong>
                                    </h5>
                                    <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="message-preview">
                        <a href="#">
                            <div class="media">
                                <span class="pull-left">
                                    <img class="media-object" src="http://placehold.it/50x50" alt="">
                                </span>
                                <div class="media-body">
                                    <h5 class="media-heading">
                                        <strong>Jonathan</strong>
                                    </h5>
                                    <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="message-footer">
                        <a href="#">Read All New Messages</a>
                    </li>
                </ul>
            </li>
            @*<li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>*@
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> @SessionHelper.GetNombreUsuarioLogueado()<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    @*<li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>*@

                    @if (SessionHelper.ExistUserInSession())
                    {
                        <li>
                            <a href="~/home/salir"><i class="fa fa-fw fa-power-off"></i> Cerrar Sesión</a>
                        </li>
                    }
                </ul>
            </li>

        </ul>

        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">

                <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#servicios"><i class="fa fa-fw fa-edit"></i> Servicios <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="servicios" class="collapse">
                        <li>
                            @Html.ActionLink("Adicionar Servicio", "AgregarServicio", "Servicios")
                        </li>
                        <li>
                            @Html.ActionLink("Consultar Servicios", "ConsultarServicios", "Servicios")
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#ventas"><i class="fa fa-fw fa-table"></i> Ventas <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="ventas" class="collapse">
                        <li>
                            @Html.ActionLink("Crear Factura", "CrearFactura", "Ventas")
                        </li>
                        <li>
                            @Html.ActionLink("Consultar Facturas", "ConsultarFacturas", "Ventas")
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#clientes"><i class="fa fa-fw fa-users"></i> Clientes <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="clientes" class="collapse">
                        <li>
                            @Html.ActionLink("Adicionar Cliente", "AdicionarCliente", "Usuarios")
                        </li>
                        <li>
                            @Html.ActionLink("Consultar Clientes", "ConsultarClientes", "Usuarios")
                        </li>
                    </ul>
                </li>
                @if (ValidadorPermisos.TienePermiso(RolesPermisos.Puede_consultar_empleado))
                {
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#empleados"><i class="fa fa-fw fa-user-md"></i> Empleados <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="empleados" class="collapse">
                            <li>
                                @Html.ActionLink("Adicionar Empleado", "AdicionarEmpleado", "Usuarios")
                            </li>
                            <li>
                                @Html.ActionLink("Consultar Empleados", "ConsultarEmpleados", "Usuarios")
                            </li>
                        </ul>
                    </li>
                }
                <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#productos"><i class="fa fa-fw fa-desktop"></i> Productos <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="productos" class="collapse">
                        <li>
                            @Html.ActionLink("Adicionar Producto", "InsertarProducto", "Productos")
                        </li>
                        <li>
                            @Html.ActionLink("Consultar Productos", "ConsultarProductos", "Productos")
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#inventarios"><i class="fa fa-fw fa-bar-chart-o"></i> Inventarios <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="inventarios" class="collapse">
                        <li>
                            @Html.ActionLink("Consultar Inventarios por Sucursal", "ConsultarSucursales", "Inventarios")
                        </li>
                        <li>
                            @Html.ActionLink("Consultar Inventario de Productos", "ConsultarInventarios", "Inventarios")
                        </li>
                        @if (ValidadorPermisos.TienePermiso(RolesPermisos.Puede_Consultar_Total_Existencias))
                        {
                            <li>
                                @Html.ActionLink("Consultar Total de existencias", "ConsultarExistenciasTotalesProductos", "Inventarios")
                            </li>
                        }
                        @if (ValidadorPermisos.TienePermiso(RolesPermisos.puede_consultar_inventario_bajas))
                        {
                            <li>
                                @Html.ActionLink("Consultar Inventario de Bajas", "ConsultarInventariosBajas", "Inventarios")
                            </li>
                        }
                    </ul>
                </li>
                <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#solicitudes"><i class="fa fa-fw fa-empire"></i> Solicitudes <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="solicitudes" class="collapse">
                        <li>
                            @Html.ActionLink("Consultar Solicitudes", "ConsultarSolicitudes", "Solicitudes")
                        </li>
                        <li>
                            @Html.ActionLink("Consultar Elementos", "ConsultarElementos", "Solicitudes")
                        </li>
                    </ul>
                </li>
                @if (ValidadorPermisos.TienePermiso(RolesPermisos.Puede_Crear_Sucursal))
                {
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#sucursales"><i class="fa fa-fw fa-home"></i> Sucursales <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="sucursales" class="collapse">
                            <li>
                                @Html.ActionLink("Crear Sucursal", "AgregarSucursal", "Inventarios")
                            </li>

                        </ul>
                    </li>
                }
            </ul>

        </div>
        <!-- /.navbar-collapse -->

    </nav>
</header>